version: '3.7'
services:
  trinkspruch:
    build: .
    ports:
      - "8002:8080"
    volumes:
      - "${PWD}/trinkspruch.sqlite:/usr/src/app/trinkspruch.sqlite:rw"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m
      timeout: 2s
      retries: 3
      start_period: 5s
